spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#        测试环境
    url: jdbc:mysql://39.96.18.59:3306/eyes?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: jdaiwe83434
  redis:
    host: 39.96.18.59
    port: 6379
    password: huzhiyuredis567
    database: 8
# 打印sql
logging:
  level:
    org.ypool.mine.pool.dao.mapper: debug
race:
  miner: t01800
server:
  port: 8001
http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000